/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package airplane;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Enumeration;


/**
 *  The GUI
 * 
 * @author Tenzin Dhargye
 */
public class AirplaneGUI extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form AirplaneGUI
     */
     
    boolean isFirstclass;
    boolean[] isTaken_FC = new boolean[4];
    boolean[] isTaken_EC = new boolean[6];
    
    int[] iFC_Seats = new int[4];
    int[] iEC_Seats = new int[6];
    
    String[] firstClass = {
        "FC1", "FC2", "FC3", "FC4", "EC1", "EC2", "EC3", "EC4", "EC5", "EC6"
    };
    
    String selected;
    
    int iSeat;
     
     
    public AirplaneGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new java.awt.Label();
        quitButton = new javax.swing.JButton();
        first1 = new javax.swing.JToggleButton();
        first3 = new javax.swing.JToggleButton();
        first2 = new javax.swing.JToggleButton();
        first4 = new javax.swing.JToggleButton();
        eco1 = new javax.swing.JToggleButton();
        eco3 = new javax.swing.JToggleButton();
        eco5 = new javax.swing.JToggleButton();
        eco2 = new javax.swing.JToggleButton();
        eco4 = new javax.swing.JToggleButton();
        eco6 = new javax.swing.JToggleButton();
        reserveButton = new javax.swing.JButton();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));

        titleLabel.setFont(new java.awt.Font("Times New Roman", 3, 60)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 200, 100));
        titleLabel.setText("Eco Airline");

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        first1.setBackground(new java.awt.Color(50, 200, 100));
        buttonGroup1.add(first1);
        first1.setForeground(new java.awt.Color(0, 0, 102));
        first1.setText("FC1");
        first1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        first1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        first3.setBackground(new java.awt.Color(50, 200, 100));
        buttonGroup1.add(first3);
        first3.setForeground(new java.awt.Color(0, 0, 102));
        first3.setText("FC3");
        first3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        first3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        first2.setBackground(new java.awt.Color(50, 200, 100));
        buttonGroup1.add(first2);
        first2.setForeground(new java.awt.Color(0, 0, 102));
        first2.setText("FC2");
        first2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        first2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        first4.setBackground(new java.awt.Color(50, 200, 100));
        buttonGroup1.add(first4);
        first4.setForeground(new java.awt.Color(0, 0, 102));
        first4.setText("FC4");
        first4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        first4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        eco1.setBackground(new java.awt.Color(50, 200, 100));
        buttonGroup1.add(eco1);
        eco1.setForeground(new java.awt.Color(0, 0, 102));
        eco1.setText("EC1");
        eco1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eco1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        eco3.setBackground(new java.awt.Color(50, 200, 100));
        buttonGroup1.add(eco3);
        eco3.setForeground(new java.awt.Color(0, 0, 102));
        eco3.setText("EC3");
        eco3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eco3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        eco5.setBackground(new java.awt.Color(50, 200, 100));
        buttonGroup1.add(eco5);
        eco5.setForeground(new java.awt.Color(0, 0, 102));
        eco5.setText("EC5");
        eco5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eco5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        eco2.setBackground(new java.awt.Color(50, 200, 100));
        buttonGroup1.add(eco2);
        eco2.setForeground(new java.awt.Color(0, 0, 102));
        eco2.setText("EC2");
        eco2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eco2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        eco4.setBackground(new java.awt.Color(50, 200, 100));
        buttonGroup1.add(eco4);
        eco4.setForeground(new java.awt.Color(0, 0, 102));
        eco4.setText("EC4");
        eco4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eco4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        eco6.setBackground(new java.awt.Color(50, 200, 100));
        buttonGroup1.add(eco6);
        eco6.setForeground(new java.awt.Color(0, 0, 102));
        eco6.setText("EC6");
        eco6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eco6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        reserveButton.setText("Reserve Seats");
        reserveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(eco3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(eco4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(eco1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(eco2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(eco5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(eco6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(first3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(first4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(first1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(first2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastNameField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(reserveButton)
                        .addGap(18, 18, 18)
                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(quitButton)
                                .addComponent(reserveButton))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eco2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eco1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eco4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eco3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eco6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eco5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Main", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Receipt", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Help", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * Exits when user clicks Quit button
     * 
     * @author Tommy Yang
     * @param evt The button event
     */
    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
       System.exit(0);
    }                                          

    /**
     * Cycles through toggle buttons when user clicks reserve, 
     * and finds the selected button. 
     * 
     * @author Tommy Yang
     * @param evt The button event
     */
    private void reserveButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        if(evt.getSource()==reserveButton) {  
            
            Enumeration<javax.swing.AbstractButton> seatButtons=buttonGroup1.getElements(); 
            
            while(seatButtons.hasMoreElements()) {  
                
                javax.swing.JToggleButton temp;  
                temp = (javax.swing.JToggleButton)seatButtons.nextElement();
                selected = temp.getText();
                
                if(temp.isSelected()) {  
                    
                    // WORK
                    
                    
                    javax.swing.JOptionPane.showMessageDialog(null,"You select : "+temp.getText());
                    //temp.setEnabled(false);
                    //temp.setBackground(Color.yellow);
                    findSeat();
                    
                    
                }  
            }            
        }
    }                                             

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirplaneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AirplaneGUI().setVisible(true);
            }
        });
    }
    
    
    /**
     * Finds an open seat
     * 
     * @author Kou Xiong     
     */
    public void findSeat() {

        for(int i : iFC_Seats) {
            
            if (isTaken_FC[i] == false) {
                
                isTaken_FC[i] = true;
                
                iSeat = i;

                switch (selected) {
                    case "FC1": 
                        first1.setEnabled(false);
                        first1.setBackground(Color.yellow);
                        break;
                    case "FC2": 
                        first2.setEnabled(false);
                        first2.setBackground(Color.yellow);
                        break;
                    case "FC3": 
                        first3.setEnabled(false); 
                        first3.setBackground(Color.yellow);
                        break;
                    case "FC4": 
                        first4.setEnabled(false);
                        first4.setBackground(Color.yellow);
                        break;
                    default:
                }
            }
        }
         for(int i : iEC_Seats)
         {
             if (isTaken_EC[i] == false)
             {
                 isTaken_EC[i] = true;
                 
                 switch (selected) {
                    case "EC1": 
                        eco1.setEnabled(false);
                        eco1.setBackground(Color.yellow);
                        break;
                    case "EC2": 
                        eco2.setEnabled(false);
                        eco2.setBackground(Color.yellow);
                        break;
                    case "EC3": 
                        eco3.setEnabled(false); 
                        eco3.setBackground(Color.yellow);
                        break;
                    case "EC4": 
                        eco4.setEnabled(false);
                        eco4.setBackground(Color.yellow);
                        break;
                    case "EC5": 
                        eco5.setEnabled(false);
                        eco5.setBackground(Color.yellow);
                        break;
                    case "EC6": 
                        eco6.setEnabled(false);
                        eco6.setBackground(Color.yellow);
                        break;
                    default:
                }
             }
         }
    }
    
    
    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton eco1;
    private javax.swing.JToggleButton eco2;
    private javax.swing.JToggleButton eco3;
    private javax.swing.JToggleButton eco4;
    private javax.swing.JToggleButton eco5;
    private javax.swing.JToggleButton eco6;
    private javax.swing.JToggleButton first1;
    private javax.swing.JToggleButton first2;
    private javax.swing.JToggleButton first3;
    private javax.swing.JToggleButton first4;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton reserveButton;
    private java.awt.Label titleLabel;
    // End of variables declaration                   
    private String test;
    /**
     *
     * @param ae
     */
    @Override
    public void actionPerformed(ActionEvent ae) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}


